backend:
  name: git-gateway
  branch: main
  identity_url: https://yokaiink.netlify.app/.netlify/identity
  gateway_url: https://yokaiink.netlify.app/.netlify/git

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

publish_mode: editorial_workflow

collections:
  - label: "Site Content"
    name: "content"
    files:
      - label: "Brand Settings"
        name: "settings"
        file: "assets/content/settings.json"
        format: "json"
        fields:
          - { label: "Studio Name", name: "name", widget: "string" }
          - { label: "Phone", name: "phone", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Address", name: "address", widget: "string" }
          - { label: "Instagram URL", name: "instagram", widget: "string" }
      - label: "Portfolio"
        name: "portfolio"
        file: "assets/content/portfolio.json"
        format: "json"
        fields:
          - label: "Portfolio Items"
            name: "items"
            widget: "list"
            summary: "{{fields.title}}"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Image", name: "src", widget: "image" }
              - { label: "Tags", name: "tags", widget: "list", field: { label: "Tag", name: "tag", widget: "string" } }
      - label: "Events"
        name: "events"
        file: "assets/content/events.json"
        format: "json"
        fields:
          - label: "Events"
            name: "items"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Date", name: "date", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
